config/routes.rb
Rails.application.routes.draw do

  resources :answers do
    collection do 
      get "post_answer_feedback"
    end
  end

  resources :questions

  resources :subjects

  get 'home/index'
  root 'home#index'
  
  resources :categories

  resources :topics do
    collection do 
      get "forums"
      get "all_questions"
      get "all_topics"
    end
  end

  resources :profiles

  resources :comments

  devise_for :users
  
  resources :users do
    collection do 
      get "members"
    end
  end

  # get 'users/index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, :reject_if => :all_blank , :allow_destroy => true

  scope :anothers, lambda {|topic_id| where "id != ?", topic_id}
  scope :another_topic_in_category, lambda {|topic_id, category_id| where "id != ? and category_id = ?", topic_id, category_id}

  def self.top_question
    sql = " select t1.*
            from topics t1, (select q.topic_id as id, count(q.topic_id) as num_question
                            from topics t, questions q
                            where t.id = q.topic_id
                            group by q.topic_id
                            order by num_question desc
                            limit 1) as t2
            where t1.id = t2.id 
          "
    topic = Topic.find_by_sql(sql).first
    unless topic
      topic = Topic.order("created_at desc").first
    end
    topic
  end

  def self.top_question_on_category(category_id)
    sql = " select t1.*
            from topics t1, (select q.topic_id as id, count(q.topic_id) as num_question
                            from topics t, questions q
                            where t.id = q.topic_id
                            and t.category_id = #{category_id}
                            group by q.topic_id
                            order by num_question desc
                            limit 1) as t2
            where t1.id = t2.id 
          "
    topic = Topic.find_by_sql(sql).first
     unless topic
      topic = Topic.where("category_id = ? ",category_id).order("created_at desc").first
    end
    topic
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:forums]

  # GET /topics
  # GET /topics.json
  def index
    # @topics = Topic.all
    @q = Topic.order("updated_at DESC").page(params[:page]).search(params[:q])
    @topics = @q.result
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @topic.attachments.build
    @categories = Category.all
  end

  # GET /topics/1/edit
  def edit
    @categories = Category.all
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def forums
    if params[:topic_id]
      @topic = Topic.find(params[:topic_id])
    elsif params[:category_id]
      @topic = Topic.top_question_on_category(params[:category_id])
    else 
      @topic = Topic.top_question
    end
    @categories = Category.all
    @topics = Topic.another_topic_in_category(@topic.id, @topic.category_id).limit(2) if @topic 
    @questions = @topic.questions.order("created_at desc") if @topic
    @top_questions = Question.order("created_at desc").limit(5)
  end


  def all_questions
    @questions = Question.all
    render :partial => "topics/right_side_top_question", :locals => {:top_questions => @questions}
  end

  def all_topics
    @topic = Topic.find(params[:current_topic])
    @topics = Topic.another_topic_in_category(@topic.id, @topic.category_id) if @topic
    render :partial => "topics/right_side_another_topics", :locals => {:topics => @topics}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :category_id, :title, :content, :status, :point, attachments_attributes: [:name, :data, :topic_id])
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_another_categories_forum.html.haml
.forum_category_box.clearfix
  - categories.each do |category|
    - if category.id == topic.category_id
      .category_name.btn.btn-warning
        = link_to category.name, forums_topics_path(:category_id => category.id)
    - else
      .category_name.btn.btn-info
        = link_to category.name, forums_topics_path(:category_id => category.id)

app/views/topics/_form.html.haml
= simple_nested_form_for(@topic) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :user_id, :value => current_user.id
    = f.label :category
    = f.select(:category_id, @categories.collect{|s| [s.name, s.id]})
    = f.input :title
    = f.input :content
    = render "shared/attachment_frm", :f => f
  .form-actions
    = f.button :submit
    = link_to "Cancel", topics_path, :class => "btn"

app/views/topics/_questions_on_topic.html.haml
#questions
  .title_page.line Questions
  .question_link.right
    = link_to "Post your question", new_question_path(:topic_id => topic.id), :class => "btn btn-primary"
  .questons_box
    - questions.each do |question|
      .question_box.clearfix
        .avatar= link_to current_user_avatar(question.user), user_path(question.user)
        .body
          .text.bold.question.title
            = link_to question.title, question_path(question)
          .question_answer_info
            .left_created.italic
              %span.blue= "#{question.created_at.strftime(I18n.t('time.format_normal'))}, "
              %span.blue= "#{question.answers.count} answers"
            .right_answer_num
              = link_to "Detail", "#", :class => "red btn_expend_question_content"
          .text.question_content.hide= question.content.html_safe

app/views/topics/_right_side_another_topics.html.haml
.side_box.clearfix
  .box_title Topics
  - topics.each do |topic|
    .text.capitalize.side_topic_title.btn.btn-success{:title => topic.title}
      = link_to truncate(topic.title, :length => 25 ), forums_topics_path(:topic_id => topic.id)
  .all_topics_link
    = link_to "All Topics", "#", :class => "btn_all_topics"

app/views/topics/_right_side_top_question.html.haml
.side_box.clearfix
  .box_title Top questions
  - top_questions.each do |question|
    .top_question_box.clearfix
      .avatar= link_to current_user_avatar(question.user), user_path(question.user)
      .info_box
        .text.font12.line18= link_to truncate(question.title, :length => 70 ), question_path(question)
  #all_question_link.all_question_link
    = link_to "All questions", "#" , :class => "btn_all_questions"

app/views/topics/_search_form.html.haml
.search_box
  = search_form_for @q do |f|
    .input.seach-query
      = f.text_field :title_cont, :class => "search-query event", :placeholder => "Enter an email"
      %button.btn{:type => "submit"} Search

app/views/topics/_topic.html.haml
#top_topic
  .title_page= @topic.title
  = topic.content
#attachments
  - topic.attachments.each do |attachment|
    .topic_image_fields
      = image_tag(attachment.data)
      .text.italic= attachment.name

app/views/topics/edit.html.haml
.title_page Editing topic

= render 'form'

app/views/topics/forums.html.haml
- if @topic
  .left_right_template_page.clearfix
    .left_content
      = render 'another_categories_forum', :categories => @categories, :topic => @topic
      = render 'topic', :topic => @topic
      = render 'questions_on_topic', :questions => @questions, :topic => @topic
    .right_side
      #right_side_all_topics
        = render 'right_side_another_topics', :topics => @topics
      #right_side_top_questions
        = render 'right_side_top_question', :top_questions => @top_questions
      = hidden_field_tag 'current_topic', @topic.id
- else
  .center THERE IS NO DATA HERE

app/views/topics/index.html.haml
.title_page Topics management
.action_box
  .link_box
    = link_to "Create new topic", new_topic_path, :class => "btn btn-primary"
  = render 'search_form'

.content_box.clear-fix
  %table.table.table-condensed
    %thead
      %tr
        %th.num.center Id
        %th.center Category
        %th.center Title
        %th.center Created_at
        %th.link_full.center Action
    %tbody
      - if @topics.size > 0
        - @topics.each_with_index do |topic, i|
          %tr
            %td.center
              = topic.id
            %td
              = topic.category.name
            %td
              = topic.title
            %td.right
              = topic.created_at.strftime(I18n.t('time.short_format')) if topic.created_at
            %td.center
              = link_to "Show", topic_path(topic)
              - if current_user.is_supper_admin or current_user.is_admin
                = link_to "Edit", edit_topic_path(topic), :class => "td_link_margin"
              - if  topic.questions.size > 0
                = link_to "Delete", '#', class: 'disable has-tooltip', title: 'This store has already had product(s), you cannot delete it'
              - else
                = link_to "Delete", topic_path(topic, authenticity_token: form_authenticity_token), method: "delete", data: {confirm: 'Are you sure?'}, class: "red"

/ %table
/   %tr
/     %th User
/     %th Category
/     %th Title
/     %th Content
/     %th Attachment
/     %th Status
/     %th Point
/     %th
/     %th
/     %th

/   - @topics.each do |topic|
/     %tr
/       %td= topic.user_id
/       %td= topic.category_id
/       %td= topic.title
/       %td= topic.content
/       %td= topic.attachment
/       %td= topic.status
/       %td= topic.point
/       %td= link_to 'Show', topic
/       %td= link_to 'Edit', edit_topic_path(topic)
/       %td= link_to 'Destroy', topic, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

/ = link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
.title_page New topic

= render 'form'

app/views/topics/show.html.haml
%p
  %b User:
  = @topic.user_id
%p
  %b Category:
  = @topic.category_id
%p
  %b Title:
  = @topic.title
%p
  %b Content:
  = @topic.content

%p
  %b Status:
  = @topic.status
%p
  %b Point:
  = @topic.point

= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Back', topics_path