config/routes.rb
Rails.application.routes.draw do

  resources :answers do
    collection do 
      get "post_answer_feedback"
    end
  end

  resources :questions

  resources :subjects

  get 'home/index'
  root 'home#index'
  
  resources :categories

  resources :topics do
    collection do 
      get "forums"
      get "all_questions"
      get "all_topics"
    end
  end

  resources :profiles

  resources :comments

  devise_for :users
  
  resources :users do
    collection do 
      get "members"
    end
  end

  # get 'users/index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  ROLE ={
    :super_admin => 1,
    :admin => 2,
    :member => 3
  }

  ROLE_TEXT ={
    1 => "super_admin",
    2 => "admin",
    3 => "member"
  }

  def is_supper_admin
    if self.role == User::ROLE[:super_admin]
      true
    else
      false
    end    
  end

  def is_admin
    if self.role == User::ROLE[:admin]
      true
    else
      false
    end    
  end

  def is_member
    if self.role == User::ROLE[:member]
      true
    else
      false
    end    
  end

  def full_name
    if self.profile
      profile.first_name  + " "+ profile.last_name
    else
      self.email
    end      
  end

  def conection_number
    25    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    # @users = User.where("role != ? and id != ?", User::ROLE[:super_admin], current_user.id)
    @q = User.order("role asc, updated_at DESC").page(params[:page]).search(params[:q])
    @users = @q.result
  end

  def members
    @users = User.where("role != ? and id != ?", User::ROLE[:super_admin], current_user.id)
  end

  def show
    @comment = Comment.new
    @comments = @user.profile.comments if @user.profile
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted.'
    # if @store.has_products?
    #   redirect_to admin_stores_path, alert: "Could not delete the store, it has already had product(s)"
    # else
    #   @store.destroy
    #   redirect_to admin_stores_path, notice: 'Store was successfully deleted.'
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :avatar, :birthday, :student_of, :address, :status, :role, :resume, :has_profile)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_avatar(user)
    if user.profile && user.profile.avatar
      image_tag(user.profile.avatar)
    else
      image_tag("common/user.png")
    end
  end
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification
  .form-inputs
    = f.input :email    
    = f.label :role
    = f.select(:role, User::ROLE )
  .form-actions
    = f.button :submit, :value => "Save"
    = link_to "cancel", user_path(@user), :class => "btn"
- if @user.profile
  = link_to "Edit profile", edit_profile_path(@user)
- else
  = link_to "Edit profile", new_profile_path(:user_id => @user.id)

app/views/users/_search_form.html.haml
.search_box
  = search_form_for @q do |f|
    .input.seach-query
      = f.text_field :email_cont, :class => "search-query event", :placeholder => "Enter an email"
      %button.btn{:type => "submit"} Search

app/views/users/edit.html.haml
.title_page Editing User Profile

= render 'form'

app/views/users/index.html.haml
.title_page Users management 

.action_box
  .link_box
    = link_to "Create new user", "#", :class => "btn btn-primary"
  = render 'search_form'

.content_box.clear-fix
  %table.table.table-condensed
    %thead
      %tr
        %th.num.center Id
        %th.center avatar
        %th.center Name
        %th.center Course
        %th.center Birthday
        %th.center Role
        %th.link_full.center Action
    %tbody
      - @users.each_with_index do |user, i|
        %tr
          %td.center
            = user.id
          %td
            .img_logo
              = link_to current_user_avatar(user), user_path(user)
          %td
            = user.full_name
          %td
            = user.profile.course  if user.profile
          %td.right
            = user.profile.birthday  if user.profile
          %td
            = User::ROLE_TEXT[user.role] 
          %td.center
            = link_to "Show", user_path(user)
            - if current_user.is_supper_admin or current_user.is_admin
              = link_to "Edit", edit_user_path(user), :class => "td_link_margin"
            - if user.is_supper_admin 
              = link_to "Delete", '#', class: 'disable has-tooltip', title: 'This store has already had product(s), you cannot delete it'
            - else
              = link_to "Delete", user_path(user, authenticity_token: form_authenticity_token), method: "delete", data: {confirm: 'Are you sure?'}, class: "red"

app/views/users/members.html.haml
.title_page Members 
- if @users
  - @users.each do |user|
    .user_profile_box.clearfix
      .avatar_field
        = link_to current_user_avatar(user), user_path(user)
      .info_field
        .text.bold= truncate(user.full_name, length: 30)
        .text= truncate(user.profile.major, length: 45) if user.profile
      .conect_number
        = link_to user.conection_number, "#"
- else
  There is not user here

app/views/users/show.html.haml
- if @user
  #top_user_info_box.clearfix
    .profile_avatar
      = current_user_avatar(@user)
    .profile_info
      %p
        %span.text.bold Email: 
        %span= @user.email
        %span.text.italic= "(#{User::ROLE_TEXT[@user.role]})" 
      - if @user.profile
        %p
          %span.text.bold Name: 
          %span= "#{@user.profile.first_name} #{@user.profile.last_name}"
        %p
          %span.text.bold Birthday: 
          %span= @user.profile.birthday
        %p
          %span.text.bold Address: 
          %span= @user.profile.address
        %p
          %span.text.bold Major: 
          %span= @user.profile.major
        %p
          %span.text.bold Resume: 
          %span= @user.profile.resume

      - else
        .text.bold.blue User has no profile
      - if @user.id == current_user.id  
        .update_profile_action
          - if @user.profile
            = link_to "Update profile", edit_profile_path(@user.profile), :class => "btn btn-primary"
          - else
            = link_to "Create profile", new_profile_path, :class => "btn btn-primary"
  #user_comment_box.clearfix
    .title_page 
      %span Comments
      %span.text.italic= "(#{@comments.size})" if @comments
    - if @comments
      .comment_info_box
        - @comments.each do |comment|
          .commnet_field.clearfix
            .current_user_avatar= link_to current_user_avatar(comment.user), user_path(comment.user)
            .comment_info_content
              .text.bold= link_to comment.user.full_name, user_path(comment.user)
              .text= comment.content
    - if current_user.id != @user.id
      .frm_comment_box.clearfix
        = simple_form_for(@comment) do |f|
          .form-inputs
            = f.hidden_field :user_id, :value => current_user.id
            = f.hidden_field :profile_id, :value => @user.profile.id
            = hidden_field_tag :comment_type, "user_comment"
            .current_user_avatar= link_to current_user_avatar(current_user), user_path(current_user)
            = f.input :content, :label => false
            = f.button :submit, :value => "Save"