config/routes.rb
Rails.application.routes.draw do

  resources :answers do
    collection do 
      get "post_answer_feedback"
    end
  end

  resources :questions

  resources :subjects

  get 'home/index'
  root 'home#index'
  
  resources :categories

  resources :topics do
    collection do 
      get "forums"
      get "all_questions"
      get "all_topics"
    end
  end

  resources :profiles

  resources :comments

  devise_for :users
  
  resources :users do
    collection do 
      get "members"
    end
  end

  # get 'users/index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, :reject_if => :all_blank , :allow_destroy => true


  STATUS ={
    :good     => 1,
    :spam     => 2,
    :normal   => 3
  }

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :topic
  belongs_to :question
  belongs_to :answer

  mount_uploader :data, MyUploader

end

app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :user
  belongs_to :subject
  has_many :topics
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy


  mount_uploader :avatar, MyUploader


end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :answers, dependent: :destroy
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, :reject_if => :all_blank , :allow_destroy => true
  
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :categories
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :attachments, dependent: :destroy

  accepts_nested_attributes_for :attachments, :reject_if => :all_blank , :allow_destroy => true

  scope :anothers, lambda {|topic_id| where "id != ?", topic_id}
  scope :another_topic_in_category, lambda {|topic_id, category_id| where "id != ? and category_id = ?", topic_id, category_id}

  def self.top_question
    sql = " select t1.*
            from topics t1, (select q.topic_id as id, count(q.topic_id) as num_question
                            from topics t, questions q
                            where t.id = q.topic_id
                            group by q.topic_id
                            order by num_question desc
                            limit 1) as t2
            where t1.id = t2.id 
          "
    topic = Topic.find_by_sql(sql).first
    unless topic
      topic = Topic.order("created_at desc").first
    end
    topic
  end

  def self.top_question_on_category(category_id)
    sql = " select t1.*
            from topics t1, (select q.topic_id as id, count(q.topic_id) as num_question
                            from topics t, questions q
                            where t.id = q.topic_id
                            and t.category_id = #{category_id}
                            group by q.topic_id
                            order by num_question desc
                            limit 1) as t2
            where t1.id = t2.id 
          "
    topic = Topic.find_by_sql(sql).first
     unless topic
      topic = Topic.where("category_id = ? ",category_id).order("created_at desc").first
    end
    topic
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :topics, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  ROLE ={
    :super_admin => 1,
    :admin => 2,
    :member => 3
  }

  ROLE_TEXT ={
    1 => "super_admin",
    2 => "admin",
    3 => "member"
  }

  def is_supper_admin
    if self.role == User::ROLE[:super_admin]
      true
    else
      false
    end    
  end

  def is_admin
    if self.role == User::ROLE[:admin]
      true
    else
      false
    end    
  end

  def is_member
    if self.role == User::ROLE[:member]
      true
    else
      false
    end    
  end

  def full_name
    if self.profile
      profile.first_name  + " "+ profile.last_name
    else
      self.email
    end      
  end

  def conection_number
    25    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def bootstrap_class_for flash_type
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end

  def highlight_list(name)
    params[name] == "true" ? "btn-info btn" : "btn"
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_avatar(user)
    if user.profile && user.profile.avatar
      image_tag(user.profile.avatar)
    else
      image_tag("common/user.png")
    end
  end
end

app/views/shared/_attachment_frm.html.haml
.attachments_fields.clearfix
  %p.title_page Attachments
  = f.fields_for :attachments do |a|
    = a.link_to_remove "-", :title => "Remove attachment", :class => "btn btn-danger btn-remove-attachment"
    = a.input :data, :label => "File"
    = a.input :name, :label => "Image info"
  .nested_action_box
    = f.link_to_add(:attachments, :href => '#', :title => "Add attachment", :class => "btn-add-attachment") do
      .btn.btn-primary +

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  .alert.fade.in{class: "#{bootstrap_class_for(type)}"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/shared/_footer.html.haml
.footer_menu_box
  %ul.footer_menu
    %li#privacy{:class => (current_page?("#")  ? "selected" : "")}
      = link_to "link 1" , "#"
    %li#refer
      = link_to "link 2" , "#"
    %li#about
      = link_to "link 3" , "#"

app/views/shared/_header.html.haml
#head-top
  #logo
    = link_to image_tag('common/logo.png'), root_path
  #main_menu
    = render 'shared/main_menu'
  #head_menu
    %ul
      - if user_signed_in?
        %li
          = image_tag("common/sprite1.png", :class => "user_info")
          %ul.main-sub-menu
            %li
              = link_to "My Account", user_path(current_user)
            %li
              = link_to "Change Password", edit_user_registration_path
            %li
              - if current_user.profile
                = link_to "Edit Profile", edit_profile_path(current_user.profile)
              - else 
                = link_to "Edit Profile", new_profile_path
            %li
              = link_to I18n.t('common.logout'), destroy_user_session_path(:authenticity_token => form_authenticity_token()), :method => :delete 
        %li.email_info= current_user.email
      - else
        %li
          = link_to new_user_registration_path , :class => "user_right_soace" do
            %i.icon-lock
            = I18n.t('common.register')
          = link_to new_user_session_path , :class => "" do
            %i.icon-lock
            = I18n.t('common.login')

app/views/shared/_jquery_te.html.erb
<script>
  $('.jqte-test').jqte();
  
  // settings of status
  var jqteStatus = true;
  $(".status").click(function()
  {
    jqteStatus = jqteStatus ? false : true;
    $('.jqte-test').jqte({"status" : jqteStatus})
  });
</script>

app/views/shared/_main_menu.html.haml
%ul
  %li
    = link_to "Home", root_path
  %li
    = link_to "About", "#"
  %li
    = link_to "Forums", forums_topics_path
  - if user_signed_in?
    %li
      = link_to "Users", members_users_path
    - if current_user.is_admin or current_user.is_supper_admin
      %li
        = link_to "Admin", "#"
        %ul.main-sub-menu
          %li
            = link_to "User management", users_path
          %li
            = link_to "Category management", categories_path
          %li
            = link_to "Topic management", topics_path

     