config/routes.rb
Rails.application.routes.draw do

  resources :answers do
    collection do 
      get "post_answer_feedback"
    end
  end

  resources :questions

  resources :subjects

  get 'home/index'
  root 'home#index'
  
  resources :categories

  resources :topics do
    collection do 
      get "forums"
      get "all_questions"
      get "all_topics"
    end
  end

  resources :profiles

  resources :comments

  devise_for :users
  
  resources :users do
    collection do 
      get "members"
    end
  end

  # get 'users/index'

end

app/models/category.rb
class Category < ActiveRecord::Base

  belongs_to :user
  belongs_to :subject
  has_many :topics
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  # GET /categories
  # GET /categories.json
  def index
    # @categories = Category.all
    @q = Category.order("updated_at DESC").page(params[:page]).search(params[:q])
    @categories = @q.result
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @subjects = Subject.all
  end

  # GET /categories/1/edit
  def edit
    @subjects = Subject.all
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :user_id, :status, :subject_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.label :subject
    = f.select(:subject_id, @subjects.collect{|s| [s.name, s.id]})
    = f.input :name
    = f.input :description
    = f.hidden_field :user_id, :value => current_user.id

  .form-actions
    = f.button :submit
    = link_to "Cancel", categories_path, :class => "btn"

app/views/categories/_search_form.html.haml
.search_box
  = search_form_for @q do |f|
    .input.seach-query
      = f.text_field :name_cont, :class => "search-query event", :placeholder => "Enter an name"
      %button.btn{:type => "submit"} Search

app/views/categories/edit.html.haml
.title_page Editing category

= render 'form'

app/views/categories/index.html.haml
.title_page Categories management

.action_box
  .link_box
    - if current_user.is_supper_admin or current_user.is_admin
      = link_to "Create new category", new_category_path, :class => "btn btn-primary"
  = render 'search_form'

.content_box.clear-fix
  %table.table.table-condensed
    %thead
      %tr
        %th.num.center Id
        %th.center Name
        %th.center Description
        %th.center Topic number
        %th.center Status
        %th.center Created_at
        %th.link_full.center Action
    %tbody
      - @categories.each_with_index do |category, i|
        %tr
          %td.center
            = category.id
          %td
            = category.name
          %td
            = category.description
          %td
            = category.topics.count
          %td.right
            = category.status
          %td
            = category.created_at.strftime("%d/%m/%Y")
          %td.center
            - if current_user.is_supper_admin or current_user.is_admin
              = link_to "Edit", edit_category_path(category), :class => "td_link_margin"
              - if category.topics.size > 0 
                = link_to "Delete", '#', class: 'disable has-tooltip', title: 'This category has already had topic(s), you cannot delete it'
              - else
                = link_to "Delete", category_path(category, authenticity_token: form_authenticity_token), method: "delete", data: {confirm: 'Are you sure?'}, class: "red"
/ %table
/   %tr
/     %th Name
/     %th Description
/     %th User
/     %th Status
/     %th
/     %th
/     %th

/   - @categories.each do |category|
/     %tr
/       %td= category.name
/       %td= category.description
/       %td= category.user_id
/       %td= category.status
/       %td= link_to 'Show', category
/       %td= link_to 'Edit', edit_category_path(category)
/       %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

/ %br

/ = link_to 'New Category', new_category_path

app/views/categories/new.html.haml
.title_page New category

= render 'form'

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Description:
  = @category.description
%p
  %b User:
  = @category.user_id
%p
  %b Status:
  = @category.status

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path